export const userTypes = {
    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    REGISTER_GUEST_INIT: 'REGISTER_GUEST_INIT',
    REGISTER_GUEST_START: 'REGISTER_GUEST_START',
    REGISTER_GUEST_SUCCESS: 'REGISTER_GUEST_SUCCESS',
    REGISTER_GUEST_FAILURE: 'REGISTER_GUEST_FAILURE',
    LOGOUT: 'LOGOUT',
    REFRESH_ACCESS_TOKEN: 'REFRESH_ACCESS_TOKEN',
    CHECKISLOGGEDIN: 'CHECKISLOGGEDIN',
    CHECKISLOGGEDINSUCCESS: 'CHECKISLOGGEDINSUCCESS',
    CHECKISLOGGEDINFAILURE: 'CHECKISLOGGEDINFAILURE',

    // setting user
    CHANGE_USER_AVATAR: 'CHANGE_USER_AVATAR',
    UPDATE_USER_INFO: 'UPDATE_USER_INFO',
}
